// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Solution.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20220121173327_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NatOrState")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Yellowstone",
                            NatOrState = "National",
                            Rating = 10,
                            State = "Wyoming, Montana, Idaho"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Zion",
                            NatOrState = "National",
                            Rating = 9,
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Barr Lake State Park",
                            NatOrState = "State",
                            Rating = 9,
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Rock Bridge State Park",
                            NatOrState = "State",
                            Rating = 8,
                            State = "Missouri"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
